### ISSUE TITLE
Java 17: module java.desktop does not "opens java.awt" to unnamed module

### ISSUE THREAD

**Issue by davy7125** [svenmeier/jorgan#9]
After a Fedora update from version 35 to version 36, jOrgan is not able to open a disposition anymore.
I have two versions of the java JDK: version 11 and version 17. With version 11.0.15 everything is working correctly but with version 17.0.3 here is the error:

```
GRAVE: bootstrapping failed
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jorgan.bootstrap.Main.<init>(Main.java:31)
	at jorgan.bootstrap.Bootstrap.start(Bootstrap.java:39)
	at jorgan.bootstrap.Bootstrap.main(Bootstrap.java:48)
Caused by: java.lang.Error: java.lang.reflect.InvocationTargetException
	at jorgan.gui.GUI.invokeOnSwing(GUI.java:212)
	at jorgan.gui.GUI$FileInit.<init>(GUI.java:194)
	at jorgan.gui.GUI.display(GUI.java:79)
	at jorgan.App.start(App.java:66)
	at jorgan.App.main(App.java:100)
	... 7 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at jorgan.gui.GUI.invokeOnSwing(GUI.java:207)
	... 11 more
Caused by: java.lang.Error: Unable to make void java.awt.EventDispatchThread.pumpEvents(java.awt.Conditional) accessible: module java.desktop does not "opens java.awt" to unnamed module @383534aa
	at spin.off.AWTReflectDispatcherFactory.<clinit>(AWTReflectDispatcherFactory.java:144)
	at spin.off.SpinOffEvaluator.<clinit>(SpinOffEvaluator.java:38)
	at spin.Spin.<clinit>(Spin.java:68)
	at jorgan.gui.OrganFrame.setSession(OrganFrame.java:305)
	at jorgan.gui.OrganFrame.openOrgan(OrganFrame.java:358)
	at jorgan.gui.GUI$FileInit.run(GUI.java:198)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Maybe this is a bug on the java JDK side.

It's mentioned [here](https://discourse.jabref.org/t/cannot-start-jabref-3-7-3-6-using-java-9-on-ubuntu-16-04/361/3) that launching a jar with an additional module would work but I probably didn't find the right module to add.

**Comment by svenmeier** [comment]
Please check the contents of the file "/usr/bin/jorgan", does it contain the following?

```
#!/bin/sh

java --illegal-access=permit -Xmx128M -jar /usr/lib/jorgan/jorgan.jar "$@"
```

**Comment by davy7125** [comment]
Except "lib" that is "lib64", I have the same line

**Comment by svenmeier** [comment]
Try changing that line to:

```
java --add-opens=java.desktop/java.awt=ALL-UNNAMED -Xmx128M -jar /usr/lib/jorgan/jorgan.jar "$@"
```

**Comment by davy7125** [comment]
This is working, thank you!

Maybe the sources of jOrgan should be adapted for this case? Or this is tied to a specific version of Fedora / JDK?

**Comment by svenmeier** [comment]
Starting with Java 17 a new parameter has to be added. I didn't notice it because I use jOrgan in headless mode only.

I've applied the change to jOrgan's sources so future releases will work out-of-the box.

Thanks for your report.
